[versions]
androidGradlePlugin = "8.2.2"
kotlin = "1.9.22"
ksp = "1.9.22-1.0.17"

lifecycle = "2.7.0"
compose = "1.6.2"
composeCompiler = "1.5.10"
material3 = "1.2.0"

hilt = "2.50"

okhttp = "4.12.0"

junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"

[libraries]
kotlinxCoroutines = "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.0"

androidxActivity = "androidx.activity:activity-compose:1.8.2"
androidxCore = "androidx.core:core-ktx:1.12.0"
androidxCoreSplash = "androidx.core:core-splashscreen:1.0.1"
androidxNavigationCompose = "androidx.navigation:navigation-compose:2.7.7"
androidxLifecycleRuntime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidxLifecycleViewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidxHiltNavigationCompose = "androidx.hilt:hilt-navigation-compose:1.2.0"
androidxProfileInstaller = "androidx.profileinstaller:profileinstaller:1.3.1"

androidxComposeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
androidxComposeUiTooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
androidxComposeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
androidxComposeFoundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
androidxComposeMaterial3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
androidxComposeMaterial3WindowSizeClass = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
androidxComposeMaterialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
androidxComposeUiTest = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }

coil = "io.coil-kt:coil-compose:2.5.0"

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

# For build-logic
androidGradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "androidGradlePlugin" }
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
hiltPlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
kspPlugin = { module = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin", version.ref = "ksp" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kspPlugin = { id = "com.google.devtools.ksp", version.ref = "ksp" }
